package guru.springframework.spring5webapp.bootstrap;

import guru.springframework.spring5webapp.domain.Book;
import guru.springframework.spring5webapp.repositories.BookRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

@Profile({"local", "default"})
@Component
public class DataInitializer implements CommandLineRunner {

    private final BookRepository bookRepository;

    public DataInitializer(BookRepository bookRepository) {
        this.bookRepository = bookRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        bookRepository.deleteAll(); // when running profiles default or local it will delete all entries in the bookRepository so we don't constantly add the same entries that are added in this method

        Book book1 = new Book("Story of Pooky, Vol. 1", "1001", "Pooky Publishing House");
        System.out.println("Before saving the value for book1's ID is: " + book1.getId());
        Book savedBook1 = bookRepository.save(book1); // automatically assigns the autogenerated value of id
        System.out.println("After saving the value for book1's ID is: " + savedBook1.getId());

        Book book2 = new Book("Story of Pooky, Vol. 2", "1002", "Pooky Publishing House");
        Book savedBook2 = bookRepository.save(book2);

        bookRepository.findAll().forEach(book -> {
            System.out.println("Book ID: " + book.getId());
            System.out.println("Book title: " + book.getTitle());
        });
    }
}
